config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'import' => 'home#create'
  delete 'delete' => 'contents#destroy'
  post 'compare' => 'comparison_result#create'
  get 'result' => 'comparison_result#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

  validates :upload_file_name, presence: true
  validates :upload_file_path, presence: true
  validates :klass_name, presence: true

  def on_record(file)
    @content = Content.new
    @content.upload_file_name = file.original_filename
    @content.upload_file_path = output_path(file.original_filename)
    @content.klass_name = to_klass_name(file.original_filename)
    @content.save!

    File.open(output_path(file.original_filename), 'w+b') do |fp|
      fp.write file.read
    end

    RecordGenerater.make(@content)
  end

  private

  def output_path(file_name)
    Rails.root.join('tmp', file_name)
  end

  def to_klass_name(file_name)
    File.basename(file_name, ".csv").capitalize
  end
end

app/models/csv_reader.rb
require 'csv'

module CsvReader

  def self.read(file_path)
    CSV.read(file_path)
  end
end

app/models/record_generater.rb
module RecordGenerater

  def self.make(content)
    @headers, *@attributes = CsvReader.read(content.upload_file_path)
    table_name = content.klass_name.downcase

    make_table(table_name)
    insert_data(table_name)
  end

  def self.delete_table(table_name)
    if connection.table_exists?(table_name)
      connection.drop_table(table_name)
    end
  end

  def self.make_class(model_name)
    if Object.const_defined?(model_name)
      Object.const_get(model_name)
    else
      klass = Class.new(ActiveRecord::Base) do |c|
        c.table_name = model_name.downcase
      end
      Object.const_set(model_name, klass)
    end
  end

  private

  def self.make_table(table_name)
    unless connection.table_exists?(table_name)
      connection.create_table(table_name, id: false) do |t|
        @headers.each do |header|
          t.string header
        end
      end
    end
  end

  def self.insert_data(table_name)
    column_name = to_string(@headers)
    @attributes.each do |attribute|
      attribute_s = to_string(attribute)
      connection.execute("insert into #{table_name}(#{column_name}) values(#{attribute_s})")
    end
  end

  def self.to_string(object)
    "'" + object.join("','") + "'"
  end

  def self.connection
    ActiveRecord::Base.connection
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comparison_result_controller.rb
class ComparisonResultController < ApplicationController

  def create
    RecordGenerater.make_class(Content.first.klass_name)
    RecordGenerater.make_class(Content.last.klass_name)

    @file01_klass = Object.const_get(Content.first.klass_name)
    @file02_klass = Object.const_get(Content.last.klass_name)

    @file1 = @file01_klass.all.pluck
    @file2 = @file02_klass.all.pluck
    # テーブルの内容を取得する
    # 比較オプションを取得する

    # 比較内容 : 指定されたカラムの要素を見て
    # 　　　　 　両方に存在する行をお互いに消してゆく
    # 　　　　 　それぞれのファイルには
    # 　　　　 　片方にしか存在しない要素が結果として残る

    # sort する
    #
    render action: "index"
  end

  def index
    @file1
    @file2
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def destroy
    content = Content.find(params[:id])
    RecordGenerater.delete_table(content.klass_name.downcase)
    content.destroy

    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @files = Content.all
  end

  def create
    if Content.count <= 1
      file = params[:file]

      if file != nil
        content = Content.new
        content.on_record(file)
      end
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comparison_result_helper.rb
module ComparisonResultHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comparison_result/index.html.erb
<h2>比較結果</h2>
<p>--------------------</p>
<div>
  <p>file_01</p>
  <% if @file1.present? %>
    <table border=1>
      <tr>
      <% @file1.each do |attr| %>
        <tr>
          <% attr.each do |h| %>
            <th><%= h %></th>
          <% end %>
        </tr>
      <% end %>
      </tr>
    </table>
  <% end %>
</div>
<p>--------------------</p>
<div>
  <p>file_02</p>
  <% if @file2.present? %>
    <table border=1>
      <tr>
      <% @file2.each do |attr| %>
        <tr>
          <% attr.each do |h| %>
            <th><%= h %></th>
          <% end %>
        </tr>
      <% end %>
      </tr>
    </table>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>mushimegane</h1>
<p>ホーム画面</p>

<h3>
  アップロードフォーム
</h3>
<div>
  <session class="import_form">
  <%= render 'shared/import_form' %>
  </session>
</div>
<p>ーーーーーーーーーーーーーーーーーーーー</p>
<div>
  <% if @files.present? %>
    <table border=1>
      <% @files.each do |file| %>
        <tr>
          <th><%= file.upload_file_name %></th>
          <th>
            <%= link_to "delete", delete_path(id: file.id), method: :delete,
            data: { confirm: "本当に削除してよろしいですか？" } %>
          </th>
        </tr>
      <% end %>
    </table>
  <% end %>
  <p>ーーーーーーーーーーーーーーーーーーーー</p>
  <div>
    <h3>比較オプション</h3>
    <%= select_tag(:values, options_for_select(['', 'id', 'first_name', 'last_name', 'email'])) %>
  </div>
  <%= form_tag({controller: "comparison_result", action: "create", method: "post"}, {multipart: true}) do %>
    <%= submit_tag "比較" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mushimegane</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_csv_data_table.html.erb
<div>
  <% if @headers.present? %>
    <table border=1>
      <tr>
        <% @headers.each do |h| %>
          <th><%= h %></th>
        <% end %>
      </tr>
      <% @attributes.each do |attribute| %>
        <tr>
          <% attribute.each do |t| %>
            <th><%= t %></th>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/shared/_import_form.html.erb
<%= form_tag({controller: "home", action: "create", method: "post"}, {multipart: true}) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "アップロード" %>
<% end %>